# 可以只留與主要組態設定檔不同的部分
# localhost 改成自己的 IP (cli > ipconfig -> IPv4 位址)

# 指定連線的資料庫驅動與 URL
spring.datasource.url=jdbc:sqlserver://YOUR_SERVER_IP:9433;databaseName=ProjectDB;encrypt=false

# Redis 連線設定
spring.data.redis.host=YOUR_SERVER_IP
spring.data.redis.port=9979
# 生產環境安全考量，禁止啟動時自動清空 Redis
app.redis.flush-on-startup=false

# RabbitMQ 連線設定
spring.rabbitmq.host=YOUR_SERVER_IP


# 彈性郵件連線設定（預設為 Maildev 本地沙盒；注入環境變數時對接 Brevo）
spring.mail.host=YOUR_SERVER_IP
spring.mail.port=9025

# 【方式二】結合 Spring 原生機制，執行自定義的 SQL 腳本，可用參數為
# - always   : 每次專案啟動時皆會執行指定的 SQL 檔案。適合初期開發階段，幫助我們每次重啟都能擁有一份乾淨的測試資料。
# - embedded : 預設值，僅在使用記憶體資料庫 (如 H2) 時才會執行腳本。若連線的是真實資料庫則不會觸發。
# - never    : 關閉執行腳本功能，通常用於正式環境防止意外覆蓋資料。
spring.sql.init.mode=never